#!/usr/bin/env python
import sys
if (len(sys.argv) < 2):
	print 'please enter your file.'
	exit (1)

fpath = sys.argv[1]
f = open(fpath, 'r')
cnt = []
for l in f:
	if (l.strip() == ''):
		cnt.append(l + '\n')
	else:
		cnt.append(l.replace('\n', ''))
f.close()

f = open(fpath, 'w')
f.writelines(cnt)
f.close()
